:title: "Image Annotation"
:description: "Annotate a specific type of object in the image. Do not use Internet Explorer for this HIT."
:reward: 0.01
:num_assignments: 1
:duration: 1800
:lifetime: 259200
:auto_approval: 259200
:frame_height: 700
:keywords:  ["image","photo","annotation"]
:qualifications:
  :approval_rate:
    :gt: 96
  :hits_approved:
    :gt: 1000
